name: Build recovery Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      VENDOR: infinix
      DEVICE: Infinix-X627STU
      ANDROID_ROOT: /home/runner/work/orangefox/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "OrangeFox Volla Phone CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"
    - name: Downloading source code
      run: |
        source of.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0 --depth=1
        repo sync -j8 -c 
        git clone https://github.com/00p513-dev/device_infinix_Infinix-X627STU device/infinix/Infinix-X627STY -b main --depth=1 
 
    - name: Build recovery
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Images
        path: /home/runner/work/orangefox/out/target/product/*/*.img
